#! /bin/bash
currenttime=$(date "+%Y.%m.%d-%H.%M.%S")
if [ -z "$1" ]
then
    echo "bash ./massive-downloader-bandcamp-dl  <put in here your root URL of bandcamp's band you want to download>"
else
    urlarray=`wget --quiet -O - $1 | grep -io '<a href=['"'"'"][^"'"'"']*['"'"'"]' | sed -e 's/^<a href=["'"'"']//i' -e 's/["'"'"']$//i' | grep \/album`
	echo $urlarray | tr ' ' '\n' > $-currenttime.tmp
	cat $-currenttime.tmp ts $1 | tr -d ' ' | while IFS= read -r line
  	do
    	python3 bandcamp-dl.py "$line"
  	done
	rm $currenttime.tmp
fi
